name: End-to-End

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - '27017-27019:27017-27019'

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Seed database
      run: ./mongoseed.sh
      working-directory: ./database

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cache Gradle artifacts (downloaded JARs, the wrapper, and any downloaded JDKs)
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/jdks
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/.gradle/') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies (npm ci)
      run: npm ci
      working-directory: ./client

    - name: Start server and run e2e tests
      run: cd server && ./gradlew run & cd client && npm run e2eci


